### ISSUE TITLE
Test issues filter in milestone view page

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#56]

**Comment by UEvgeniy** [comment]
До 19.01 23:59

**Comment by UEvgeniy** [comment]
Tested next cases:
1. Open MilestoneActivity for MS with:
   a) 8 opened, 0 closed issues - success
   b) 2 opened, 2 closed issues - success
   c) 0 opened, 4 closed issues - success
   d) 0 opened, 0 closed issues - success
   e) empty due to date - crush (issue #65 opened)
   f) empty description - success
2. Filter open and closed issues - success
3. Changed next milestones properties:
   a) Title - success
   b) Description - failed (issue #66 opened)
   c) Due to date: 
add - can't test (watch 1e)
remove - failed (issue #64 opened)
replace - success
