### ISSUE TITLE
Incorrect transition between issue and milestone activities

### ISSUE THREAD

**Issue by UEvgeniy** [AndreySBer/ForkHub#71]
1. open repo
2. open milestones list
3. select milestone with opened issues
4. select any issue.
5. clicking on back button (arrow to the left on screen) redirects to repository activity with tabs instead of milestone view. Clicking on touch button on smartphone redirects correctly.

**Comment by phansier** [comment]
Due to comment of Jonan https://github.com/jonan/ForkHub/pull/343#discussion_r170665910 this back button is "up" button and should always lead not to the previous screen, but to the up screen (repositories, as it was before).
Need to revert changes in https://github.com/AndreySBer/ForkHub/tree/pr_comments_fix
